import type {
  Project,
  ProjectActivity,
  ProjectFileSection,
  ProjectShare,
  Workspace,
} from "@/types/workspace"

const MB = 1024 * 1024

export const workspaceList: Workspace[] = [
  {
    id: "ws-hightool",
    name: "Hightool",
    plan: "Team",
    memberCount: 14,
  },
  {
    id: "ws-studio",
    name: "Northline Studio",
    plan: "Pro",
    memberCount: 6,
  },
  {
    id: "ws-growth",
    name: "Growth Ops",
    plan: "Team",
    memberCount: 9,
  },
]

export const workspaceProjects: Record<string, Project[]> = {
  "ws-hightool": [
    {
      id: "cloudkitchen",
      name: "CloudKitchen",
      description: "Client delivery workspace for launch videos, brand assets, and final handoff links.",
      status: "Active",
      updatedAt: "2 hours ago",
      fileCount: 18,
      shareCount: 6,
      members: ["John", "Sarah", "Mike", "Aisha"],
      isFavorite: true,
    },
    {
      id: "nike-campaign",
      name: "Nike Campaign",
      description: "Paid social and ad creative production with weekly version reviews.",
      status: "Active",
      updatedAt: "Yesterday",
      fileCount: 27,
      shareCount: 9,
      members: ["Riya", "Alex", "Cam", "Jules"],
      isFavorite: true,
    },
    {
      id: "website-redesign",
      name: "Website Redesign",
      description: "Homepage and product page deliverables for the Q3 relaunch.",
      status: "Active",
      updatedAt: "3 days ago",
      fileCount: 13,
      shareCount: 3,
      members: ["Noah", "Emma", "Ivy"],
      isFavorite: false,
    },
    {
      id: "marketing-assets",
      name: "Marketing Assets",
      description: "Shared collateral repository for evergreen campaigns and sales handoff.",
      status: "Archived",
      updatedAt: "2 weeks ago",
      fileCount: 42,
      shareCount: 14,
      members: ["Sanjay", "Mia", "Leo"],
      isFavorite: false,
    },
    {
      id: "internal-branding",
      name: "Internal Branding",
      description: "Brand guidelines and presentation templates used across teams.",
      status: "Paused",
      updatedAt: "Last month",
      fileCount: 9,
      shareCount: 2,
      members: ["Parker", "Tina"],
      isFavorite: false,
    },
  ],
  "ws-studio": [
    {
      id: "frameio-cut",
      name: "Frame.io Cut",
      description: "Review-ready edit exports for asynchronous client approvals.",
      status: "Active",
      updatedAt: "5 hours ago",
      fileCount: 11,
      shareCount: 5,
      members: ["Mika", "Ari", "Rohan"],
      isFavorite: true,
    },
    {
      id: "lookbook-ss27",
      name: "Lookbook SS27",
      description: "Photography selects and retouch rounds for seasonal launch.",
      status: "Active",
      updatedAt: "4 days ago",
      fileCount: 33,
      shareCount: 8,
      members: ["Jin", "Ari", "Kai"],
      isFavorite: false,
    },
    {
      id: "launch-deck",
      name: "Launch Deck",
      description: "Investor-facing deck iterations and final snapshot exports.",
      status: "Draft",
      updatedAt: "1 week ago",
      fileCount: 6,
      shareCount: 1,
      members: ["Nora", "Luis"],
      isFavorite: false,
    },
  ],
  "ws-growth": [
    {
      id: "q3-campaign",
      name: "Q3 Campaign",
      description: "Campaign-level file delivery across paid and lifecycle channels.",
      status: "Active",
      updatedAt: "Today",
      fileCount: 15,
      shareCount: 7,
      members: ["Inez", "Kunal", "Ava"],
      isFavorite: true,
    },
    {
      id: "partner-kit",
      name: "Partner Kit",
      description: "Co-marketing templates and approved partner logos.",
      status: "Active",
      updatedAt: "2 days ago",
      fileCount: 22,
      shareCount: 4,
      members: ["Mason", "Ava", "Theo"],
      isFavorite: false,
    },
    {
      id: "webinar-series",
      name: "Webinar Series",
      description: "Recording packages, transcripts, and event recap snapshots.",
      status: "Archived",
      updatedAt: "3 weeks ago",
      fileCount: 31,
      shareCount: 12,
      members: ["Liam", "Rhea"],
      isFavorite: false,
    },
  ],
}

export const workspaceFavoriteProjectIds: Record<string, string[]> = {
  "ws-hightool": ["cloudkitchen", "nike-campaign"],
  "ws-studio": ["frameio-cut"],
  "ws-growth": ["q3-campaign"],
}

export const workspaceRecentProjectIds: Record<string, string[]> = {
  "ws-hightool": ["website-redesign", "marketing-assets", "internal-branding"],
  "ws-studio": ["lookbook-ss27", "launch-deck", "frameio-cut"],
  "ws-growth": ["partner-kit", "q3-campaign", "webinar-series"],
}

export const projectFilesById: Record<string, ProjectFileSection[]> = {
  cloudkitchen: [
    {
      id: "cloud-videos",
      title: "Videos",
      files: [
        {
          id: "intro-mp4",
          name: "intro.mp4",
          type: "video",
          currentVersion: "v5",
          updatedAt: "2 hours ago",
          updatedAtEpoch: 1_722_000_200,
          sizeLabel: "142 MB",
          sizeBytes: 142 * MB,
          versions: [
            {
              id: "intro-v5",
              label: "v5",
              uploadedBy: "John",
              uploadedAt: "2 hours ago",
              isCurrent: true,
            },
            {
              id: "intro-v4",
              label: "v4",
              uploadedBy: "Sarah",
              uploadedAt: "Yesterday",
              isCurrent: false,
            },
            {
              id: "intro-v3",
              label: "v3",
              uploadedBy: "John",
              uploadedAt: "Last week",
              isCurrent: false,
            },
          ],
        },
        {
          id: "outro-mp4",
          name: "outro.mp4",
          type: "video",
          currentVersion: "v2",
          updatedAt: "Yesterday",
          updatedAtEpoch: 1_721_913_000,
          sizeLabel: "88 MB",
          sizeBytes: 88 * MB,
          versions: [
            {
              id: "outro-v2",
              label: "v2",
              uploadedBy: "Sarah",
              uploadedAt: "Yesterday",
              isCurrent: true,
            },
            {
              id: "outro-v1",
              label: "v1",
              uploadedBy: "Mike",
              uploadedAt: "4 days ago",
              isCurrent: false,
            },
          ],
        },
      ],
    },
    {
      id: "cloud-branding",
      title: "Branding",
      files: [
        {
          id: "logo-ai",
          name: "logo.ai",
          type: "design",
          currentVersion: "v3",
          updatedAt: "3 days ago",
          updatedAtEpoch: 1_721_813_000,
          sizeLabel: "9.8 MB",
          sizeBytes: 9_800_000,
          versions: [
            {
              id: "logo-v3",
              label: "v3",
              uploadedBy: "Aisha",
              uploadedAt: "3 days ago",
              isCurrent: true,
            },
            {
              id: "logo-v2",
              label: "v2",
              uploadedBy: "John",
              uploadedAt: "Last week",
              isCurrent: false,
            },
            {
              id: "logo-v1",
              label: "v1",
              uploadedBy: "Aisha",
              uploadedAt: "2 weeks ago",
              isCurrent: false,
            },
          ],
        },
        {
          id: "logo-png",
          name: "logo.png",
          type: "image",
          currentVersion: "v4",
          updatedAt: "2 days ago",
          updatedAtEpoch: 1_721_845_000,
          sizeLabel: "1.3 MB",
          sizeBytes: 1_300_000,
          versions: [
            {
              id: "logo-png-v4",
              label: "v4",
              uploadedBy: "Mike",
              uploadedAt: "2 days ago",
              isCurrent: true,
            },
            {
              id: "logo-png-v3",
              label: "v3",
              uploadedBy: "Mike",
              uploadedAt: "5 days ago",
              isCurrent: false,
            },
          ],
        },
      ],
    },
    {
      id: "cloud-documents",
      title: "Documents",
      files: [
        {
          id: "guidelines-pdf",
          name: "guidelines.pdf",
          type: "document",
          currentVersion: "v2",
          updatedAt: "Last week",
          updatedAtEpoch: 1_721_690_000,
          sizeLabel: "3.4 MB",
          sizeBytes: 3_400_000,
          versions: [
            {
              id: "guide-v2",
              label: "v2",
              uploadedBy: "Sarah",
              uploadedAt: "Last week",
              isCurrent: true,
            },
            {
              id: "guide-v1",
              label: "v1",
              uploadedBy: "John",
              uploadedAt: "2 weeks ago",
              isCurrent: false,
            },
          ],
        },
      ],
    },
  ],
  "nike-campaign": [
    {
      id: "nike-videos",
      title: "Videos",
      files: [
        {
          id: "nike-cutdown",
          name: "cutdown-15s.mp4",
          type: "video",
          currentVersion: "v3",
          updatedAt: "Yesterday",
          updatedAtEpoch: 1_721_913_500,
          sizeLabel: "62 MB",
          sizeBytes: 62 * MB,
          versions: [
            {
              id: "nike-cutdown-v3",
              label: "v3",
              uploadedBy: "Riya",
              uploadedAt: "Yesterday",
              isCurrent: true,
            },
            {
              id: "nike-cutdown-v2",
              label: "v2",
              uploadedBy: "Alex",
              uploadedAt: "3 days ago",
              isCurrent: false,
            },
          ],
        },
      ],
    },
  ],
  "website-redesign": [
    {
      id: "site-docs",
      title: "Documents",
      files: [
        {
          id: "wireframes-pdf",
          name: "wireframes.pdf",
          type: "document",
          currentVersion: "v4",
          updatedAt: "3 days ago",
          updatedAtEpoch: 1_721_813_500,
          sizeLabel: "6.2 MB",
          sizeBytes: 6_200_000,
          versions: [
            {
              id: "wireframes-v4",
              label: "v4",
              uploadedBy: "Noah",
              uploadedAt: "3 days ago",
              isCurrent: true,
            },
            {
              id: "wireframes-v3",
              label: "v3",
              uploadedBy: "Emma",
              uploadedAt: "Last week",
              isCurrent: false,
            },
          ],
        },
      ],
    },
  ],
  "marketing-assets": [
    {
      id: "mkt-images",
      title: "Branding",
      files: [
        {
          id: "hero-pack",
          name: "hero-pack.png",
          type: "image",
          currentVersion: "v7",
          updatedAt: "2 weeks ago",
          updatedAtEpoch: 1_721_210_000,
          sizeLabel: "12 MB",
          sizeBytes: 12 * MB,
          versions: [
            {
              id: "hero-pack-v7",
              label: "v7",
              uploadedBy: "Sanjay",
              uploadedAt: "2 weeks ago",
              isCurrent: true,
            },
          ],
        },
      ],
    },
  ],
  "internal-branding": [
    {
      id: "internal-docs",
      title: "Documents",
      files: [
        {
          id: "voice-tone",
          name: "voice-and-tone.pdf",
          type: "document",
          currentVersion: "v1",
          updatedAt: "Last month",
          updatedAtEpoch: 1_720_990_000,
          sizeLabel: "2.2 MB",
          sizeBytes: 2_200_000,
          versions: [
            {
              id: "voice-tone-v1",
              label: "v1",
              uploadedBy: "Parker",
              uploadedAt: "Last month",
              isCurrent: true,
            },
          ],
        },
      ],
    },
  ],
  "frameio-cut": [],
  "lookbook-ss27": [],
  "launch-deck": [],
  "q3-campaign": [],
  "partner-kit": [],
  "webinar-series": [],
}

export const projectSharesById: Record<string, ProjectShare[]> = {
  cloudkitchen: [
    {
      id: "cloud-client-review",
      name: "Client Review Link",
      type: "Dynamic Share",
      createdAt: "May 28, 2026",
      expiresAt: "Jun 15, 2026",
      passwordProtected: true,
      viewCount: 84,
      downloadCount: 12,
    },
    {
      id: "cloud-final-delivery",
      name: "Final Delivery Snapshot",
      type: "Snapshot Share",
      createdAt: "May 25, 2026",
      expiresAt: "Never",
      passwordProtected: false,
      viewCount: 40,
      downloadCount: 18,
    },
    {
      id: "cloud-social-pack",
      name: "Social Pack",
      type: "Dynamic Share",
      createdAt: "May 20, 2026",
      expiresAt: "Jun 20, 2026",
      passwordProtected: true,
      viewCount: 29,
      downloadCount: 9,
    },
  ],
  "nike-campaign": [
    {
      id: "nike-weekly",
      name: "Weekly Review",
      type: "Dynamic Share",
      createdAt: "May 29, 2026",
      expiresAt: "Jun 10, 2026",
      passwordProtected: true,
      viewCount: 52,
      downloadCount: 6,
    },
  ],
  "website-redesign": [
    {
      id: "site-handoff",
      name: "Design Handoff",
      type: "Snapshot Share",
      createdAt: "May 26, 2026",
      expiresAt: "Never",
      passwordProtected: false,
      viewCount: 19,
      downloadCount: 5,
    },
  ],
  "marketing-assets": [],
  "internal-branding": [],
  "frameio-cut": [],
  "lookbook-ss27": [],
  "launch-deck": [],
  "q3-campaign": [],
  "partner-kit": [],
  "webinar-series": [],
}

export const projectActivityById: Record<string, ProjectActivity[]> = {
  cloudkitchen: [
    {
      id: "a-cloud-1",
      type: "upload",
      message: "John uploaded intro.mp4 v5",
      createdAt: "2 hours ago",
    },
    {
      id: "a-cloud-2",
      type: "view",
      message: "Sarah viewed Client Review share",
      createdAt: "5 hours ago",
    },
    {
      id: "a-cloud-3",
      type: "snapshot",
      message: "Mike created Final Delivery snapshot",
      createdAt: "Yesterday",
    },
    {
      id: "a-cloud-4",
      type: "restore",
      message: "John restored logo.ai v3",
      createdAt: "Last week",
    },
  ],
  "nike-campaign": [
    {
      id: "a-nike-1",
      type: "upload",
      message: "Riya uploaded cutdown-15s.mp4 v3",
      createdAt: "Yesterday",
    },
  ],
  "website-redesign": [
    {
      id: "a-site-1",
      type: "snapshot",
      message: "Noah created Design Handoff snapshot",
      createdAt: "3 days ago",
    },
  ],
  "marketing-assets": [],
  "internal-branding": [],
  "frameio-cut": [],
  "lookbook-ss27": [],
  "launch-deck": [],
  "q3-campaign": [],
  "partner-kit": [],
  "webinar-series": [],
}
